name: Apply Patches and Build
on: [push, pull_request, workflow_dispatch]

env:
  DALAMUD_VERSION: 9.1.0.2
  LAUNCHER_VERSION: 6.3.14-beta9

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - name: Set global git user
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Checkout patches
        uses: actions/checkout@v4
      - name: Checkout Dalamud
        uses: actions/checkout@v4
        with:
          repository: 'ottercorp/Dalamud'
          path: '.\Dalamud'
          submodules: recursive
          fetch-depth: 0
      - name: Checkout Launcher
        uses: actions/checkout@v4
        with:
          repository: 'ottercorp/FFXIVQuickLauncher'
          path: '.\FFXIVQuickLauncher'
          submodules: recursive
          fetch-depth: 0
      - name: Apply Dalamud Patches
        working-directory: .\Dalamud
        run: |
          git checkout -b patched $env:DALAMUD_VERSION
          Get-ChildItem ..\patches\Dalamud\*.cherry | % {$_.FullName} | % { Get-Content $_ } | git cherry-pick -X theirs --stdin
          Get-ChildItem ..\patches\Dalamud\*.patch | % {$_.FullName} | % { Get-Content $_ } | git apply --whitespace=fix
          git log --oneline -n 5
          git diff --name-status
      - name: Apply Launcher Patches
        working-directory: .\FFXIVQuickLauncher
        run: |
          git checkout -b patched $env:LAUNCHER_VERSION
          Get-ChildItem ..\patches\FFXIVQuickLauncher\*.cherry | % {$_.FullName} | % { Get-Content $_ } | git cherry-pick -X theirs --stdin
          Get-ChildItem ..\patches\FFXIVQuickLauncher\*.patch | % {$_.FullName} | % { Get-Content $_ } | git apply --whitespace=fix
          git log --oneline -n 5
          git diff --name-status
      - name: (Dalamud) Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'
      - name: (Dalamud) Build Dalamud Core
        working-directory: .\Dalamud
        run: .\build.ps1 CompileDalamud
      - name: (FFXIVQuickLauncher) Restore Nuget Packages
        working-directory: .\FFXIVQuickLauncher
        run: |
          cd .\src\
          dotnet restore
          cd ..
      - name: (FFXIVQuickLauncher) Build DotNet4 Master
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
            .\MSBuild.exe $Env:GITHUB_WORKSPACE\FFXIVQuickLauncher\src\XIVLauncher.sln /t:Build /p:Configuration=ReleaseNoUpdate
      - name: Arrange files
        run: |
          mkdir XIVLauncherCN && cd $_
          mkdir app-$env:LAUNCHER_VERSION
          cp ..\FFXIVQuickLauncher\src\bin\XIVLauncher.Common.dll .\app-$env:LAUNCHER_VERSION\
          mkdir Roaming && cd $_
          mkdir addon && cd $_
          mkdir Hooks && cd $_
          mkdir $env:DALAMUD_VERSION
          cp ..\Dalamud\bin\Release\Dalamud.dll .\$env:DALAMUD_VERSION\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: patched-artifact
          path: .\XIVLauncherCN\